### ISSUE TITLE
账号都注册不了

### ISSUE THREAD

**Issue by baicel77** [xiaojunnanya/easy_pan#1]
注册账号的功能，提示邮箱账号不存在，注册不了

<img width="511" alt="Snipaste_2024-01-13_12-37-44" src="https://github.com/xiaojunnanya/easy_pan/assets/86587796/ca8878a8-0249-4364-9231-f299a76d5571">

**Comment by kbws13** [comment]
> 注册账号的功能，提示邮箱账号不存在，注册不了
> 
> <img alt="Snipaste_2024-01-13_12-37-44" width="511" src="https://private-user-images.githubusercontent.com/86587796/296419026-ca8878a8-0249-4364-9231-f299a76d5571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMjE5NDksIm5iZiI6MTcwNTEyMTY0OSwicGF0aCI6Ii84NjU4Nzc5Ni8yOTY0MTkwMjYtY2E4ODc4YTgtMDI0OS00MzY0LTkyMzEtZjI5OWE3NmQ1NTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA0NTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMzM2Y2IxODU4NDA2NzhjOGEyYzExY2NmN2I3YmVjOTE5ODVjODBjNDM0NTE1MThjZTZjOGNiYTE3NDczNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LPT7YslHErLB_S8-LdPJUoiR1IIwOwmYM8dZQULi8LQ">

这是重置密码的接口，不是注册的接口

**Comment by baicel77** [comment]
那怎么登陆

**Comment by kbws13** [comment]
> 那怎么登陆

1、进入注册页面
![image](https://github.com/xiaojunnanya/easy_pan/assets/90507950/78295df9-daf2-4360-b7f2-164fa39a6389)
2、输入邮箱，然后获取验证码，填写昵称、密码和验证码注册账号
![image](https://github.com/xiaojunnanya/easy_pan/assets/90507950/b5b46648-4a8a-4d80-8da0-53bef62493ab)

**Comment by baicel77** [comment]
就是这个页面注册不了，哥们，注册页面调的是重置密码接口

**Comment by kbws13** [comment]
> 就是这个页面注册不了，哥们，注册页面调的是重置密码接口

那就是它写的有bug了😂

**Comment by xiaojunnanya** [comment]
感谢指出问题，已解决
